// Generated by Wrangler on Mon May 06 2024 14:49:39 GMT+0200 (Central European Summer Time)
// by running `wrangler types worker-env.d.ts`

type Env = {
  TURSO_URL: string;
  TURSO_AUTH_TOKEN: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
};
